image: docker:19.03.12

services:
  - docker:19.03.12-dind

before_script:
  - docker build -t lohith/docker-react -f Dockerfile.dev .

build:
  stage: build
  script: 
    - docker run -e CI=true lohith/docker-react npm run test -- --coverage

