image: docker:latest

services:
  - docker:dind

before_script:
  - docker build -t lohith/docker-react -f Dockerfile.dev .

build:
  stage: build
  script: 
    - docker run -e CI=true lohith/docker-react npm run test -- --coverage

