sudo: required
services:
    - docker

before_install: 
    - docker build -t lohith/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true lohith/docker-react npm run test -- --coverage